CREATE SEQUENCE user_seq INCREMENT 1 START 1;

CREATE SEQUENCE difficulty_seq INCREMENT 1 START 1;

CREATE SEQUENCE category_seq INCREMENT 1 START 1;

CREATE SEQUENCE tag_seq INCREMENT 1 START 1;

CREATE SEQUENCE constraint_seq INCREMENT 1 START 1;

CREATE SEQUENCE role_seq INCREMENT 1 START 1;

CREATE SEQUENCE example_seq INCREMENT 1 START 1;

CREATE SEQUENCE submission_seq INCREMENT 1 START 1;

CREATE SEQUENCE editorial_seq INCREMENT 1 START 1;

CREATE SEQUENCE problem_seq INCREMENT 1 START 1;

CREATE SEQUENCE rating_seq INCREMENT 1 START 1;